plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.ispysignaling'
version = '0.1.0'

android {
  namespace "expo.modules.ispysignaling"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("org.nanohttpd:nanohttpd:2.3.1")
  implementation("org.nanohttpd:nanohttpd-websocket:2.3.1")
}
